### ISSUE TITLE
lIVER SEGMENTATION USING MONAI AND PYTORCH

### ISSUE THREAD

**Issue by rahulrajamani31** [amine0110/amine0110#1]
![image](https://user-images.githubusercontent.com/92998472/181880666-0560e249-76c3-4ab4-abf7-0ef8d8292517.png)

BRO I HAVE USED UR CODE BUT MY TESTING DATA OUTPUT IS WRONG WHAT IS WRONG WITH THIS OUTPUT

**Comment by rahulrajamani31** [comment]
bro do anyone have any idea about this

**Comment by amine0110** [comment]
Hello,

What is the your usecase?
